apiVersion: v1
kind: Service
metadata:
  name: jira
  labels:
    app: jira
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jira
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: jira
  labels:
    app: jira
spec:
  selector:
    matchLabels:
      app: jira
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jira
        tier: frontend
    spec:
      containers:
        - image: cptactionhank/atlassian-jira:latest
          name: jira
          ports:
            - containerPort: 8080
              name: jira
