apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  ports:
    - port: 9000
  selector:
    app: sonarqube
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarqube
        tier: frontend
    spec:
      containers:
        - image: sonarqube
          name: sonarqube
          ports:
            - containerPort: 9000
              name: sonarqube
